apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: mcpeeker
type: Opaque
data:
  username: {{ .Values.global.postgres.username | b64enc }}
  password: {{ .Values.global.postgres.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: mcpeeker
type: Opaque
data:
  username: {{ .Values.global.clickhouse.username | b64enc }}
  password: {{ .Values.global.clickhouse.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: anthropic-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: mcpeeker
type: Opaque
data:
  api-key: {{ .Values.judge.anthropicApiKey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: mcpeeker
type: Opaque
data:
  secret: {{ .Values.registryApi.jwtSecret | b64enc }}
